import type { NextPage } from "next";
import Head from "next/head";
// this is a weird error, the import works, but TypeScript seems unable to understand it
// @ts-ignore
import { getSumOfTwoRandomNumbers } from "@yarn-workspaces/utils";
import { Button } from "@yarn-workspaces/ui";

const Home: NextPage = () => {
  const sumOfTwoRandomNums = getSumOfTwoRandomNumbers();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>{getSumOfTwoRandomNumbers()}</Button>
    </div>
  );
};

export default Home;
