import type { NextPage } from "next";
import Head from "next/head";
// TODO figure out why there's a TS error, even though the page works just fine
// @ts-ignore
import { getSumOfTwoRandomNumbers } from "@yarn-workspaces/utils";
import { Button } from "@yarn-workspaces/styled-components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ borderWidth: "1" }}>
        <Button>styled components</Button>
        <Button>{getSumOfTwoRandomNumbers()}</Button>
      </div>
    </div>
  );
};

export default Home;
