import type { NextPage } from "next";
import Head from "next/head";
// TODO figure out why there's a TS error, even though the page works just fine
// @ts-ignore
import { getSumOfTwoRandomNumbers } from "@yarn-workspaces/utils";
import { Button as ButtonStyled } from "@yarn-workspaces/styled-components";
import { Button as ButtonEmotion } from "@yarn-workspaces/emotion";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ButtonStyled>styled components</ButtonStyled>
      <ButtonStyled>{getSumOfTwoRandomNumbers()}</ButtonStyled>
      <hr />
      <ButtonEmotion>emotion components</ButtonEmotion>
      <ButtonEmotion>{getSumOfTwoRandomNumbers()}</ButtonEmotion>
    </div>
  );
};

export default Home;
